#baseURL: "http://example.org/"
theme: hugo-universal-theme

languageCode: ru
defaultContentLanguage: ru
googleAnalytics: ''

title: "Портфолио"

params:
  viewMorePostLink: /blog/
  author: DevCows
  defaultKeywords:
    - devcows
    - hugo
    - go
  mainSections:
    - blog
  defaultDescription: Site template made by Devcows using Hugo

  # Social media
  facebook_site: '' # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
  twitter_site: GoHugoIO # the Twitter handle of your site (without the '@')
  default_sharing_image: img/sharing-default.png

  # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget)
  enableGoogleMaps: true
  googleMapsApiKey: AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY
  latitude: '-12.043333'
  longitude: '-77.028333'

  # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
  style: default

  # Enable the contact form by entering your Formspree.io endpoint url
  formspree_action: 'https://formspree.io/sample/of/endpoint'
  contact_form_ajax: false

  enableRecaptchaInContactForm: false
  googleRecaptchaKey: site_key_for_google_recaptcha

  about_us: >-
    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada
    fames ac turpis egestas.</p>
  copyright: 'Copyright (c) 2015 - 2016, YourCompany; all rights reserved.'

  # Format dates with Go's time formatting
  date_format: 'January 2, 2006'

  dropdown_mouse_over: false

  disabled_logo: false
  logo_text: Universal

  logo: img/logo.png
  logo_small: img/logo-small.png
  contact_url: /contact
  address: |-
    <p class="text-uppercase"><strong>Universal Ltd.</strong>
            <br>13/25 New Avenue
            <br>Newtown upon River
            <br>45Y 73J
            <br>England
            <br>
            <strong>Great Britain</strong>
          </p>

  # Enable or disable top bar with social icons
  topbar:
    enable: true
    text: >-
      <p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or
      hello@universal.com.</p>
            <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
            <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
            </p>

  # Enable and disable widgets for the right sidebar
  widgets:
    categories: true
    tags: true
    search: true
  carouselCustomers:
    items: 6
    auto_play: false
    slide_speed: 2000
    pagination_speed: 1000
  carouselTestimonials:
    items: 4
    auto_play: false
    slide_speed: 2000
    pagination_speed: 1000
  carouselHomepage:
    enable: true
    auto_play: true
    slide_speed: 2000
    pagination_speed: 1000
  features:
    enable: true
    cols: 3  # Default: 3, Available values 2,3,4,6
  testimonials:
    enable: true
    title: Testimonials
    subtitle: >-
      We have worked with many clients and we always like to hear they come out
      from the cooperation happy and satisfied. Have a look what our clients
      said about us.
  see_more:
    enable: true
    icon: far fa-file-alt
    title: Do you want to see more?
    subtitle: >-
      We have prepared for you more than 40 different HTML pages, including 5
      variations of homepage.
    link_url: '#'
    link_text: Check other homepages
  clients:
    enable: true
    title: Our Clients
    subtitle: ''
  recent_posts:
    enable: true
    title: From our blog
    subtitle: >-
      Pellentesque habitant morbi tristique senectus et netus et malesuada fames
      ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
      tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
      Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
    hide_summary: false
  footer:
    recent_posts:
      enable: true

# number of words of summarized post content (default 70)
summaryLength: 70

# Define the number of posts per page
paginate: 10

# not pluralize title pages by default
pluralizelisttitles: false

permalinks:
  blog: "/blog/:year/:month/:day/:filename/"

taxonomies:
  category: categories
  tag: tags
  author: authors
