name: deploy

on:
  workflow_dispatch: {}
  push:
    branches: [master, main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-pages:
    permissions:
      pages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: peaceiris/actions-hugo@v2
        with: {hugo-version: 0.101.0, extended: true}

      - run: hugo --minify -d ./dist

      - run: tar --dereference --hard-dereference -C ./dist -cvf ${{ runner.temp }}/artifact.tar .

      - uses: actions/upload-artifact@v3
        with:
          name: github-pages # don't change this
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1

      - {uses: actions/deploy-pages@v1, id: deployment}
